apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pingpong
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-number
          persistentVolumeClaim:
            claimName: log-pong-claim
      containers:
      - image: chrysozalo/pingpong:3
        name: pingpong
        imagePullPolicy: IfNotPresent
        env:
        - name: FILE_URL
          value: "/tmp/data/number.txt"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-number
          mountPath: /tmp/data # TODO: Add to this and Log deployment url env var
        resources: {}
status: {}
