apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: logoutput
  name: logoutput
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: logoutput
    spec:
      volumes:
      - name: shared-number
        persistentVolumeClaim:
          claimName: log-pong-claim
      containers:
      - image: chrysozalo/log-output:4
        name: log-output
        imagePullPolicy: IfNotPresent
        env:
        - name: FILE_URL
          value: "/tmp/data/number.txt"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: shared-number
            mountPath: /tmp/data
        resources: {}
status: {}
