apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todo-deploy
  name: todo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-deploy
    spec:
      volumes:
        - name: cashed-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
      - image: chrysozalo/todo-app:14
        name: todo-app
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cashed-image
          mountPath: /tmp/images
        resources: {}
status: {}
